name: Docker-miko

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Download amd64 binary
      if: matrix.arch == 'amd64'
      run: |
        mkdir -p binary/amd64
        curl -L -o binary/amd64/app.tar "https://wetransfer.com/download/local-bartender?id=eyJhcGlCYXNlIjoiL2FwaS92NCIsImRkUHJveHlCYXNlIjoiaHR0cHM6Ly9sb2NhbC1iYXJ0ZW5kZXItZGQtcHJveHkud2V0cmFuc2Zlci5uZXQvYXBpIiwidHJhbnNmZXJJZCI6IjRiMjJkZDdjZDkyMGI4NDAyMTVmMWZiYjIxZWYwZGYyMjAyNTA4MDcxNDIyMDAiLCJzZWNyZXQiOiI0YWU1YzQiLCJpbnRlbnQiOiJzaW5nbGVfZmlsZSIsInNob3VsZFVzZU5ld0hhbmRsZUZsb3ciOiJ0cnVlIiwiZmlsZUlkcyI6IjMwNTgyNDAwMzkyYzNiODk0MmJlYjkwZWM0N2Q4YjQ4MjAyNTA4MDcxNDIzMTMiLCJhY2Nlc3NUb2tlbiI6ImV5SmhiR2NpT2lKU1V6STFOaUlzSW5SNWNDSTZJa3BYVkNJc0ltdHBaQ0k2SW14RE0wSkZVRlJPTXpCalRubDVjVXhJY1RWZlNWOXRObDgzVGxCaVpFbHNiRXhvVGxZM09VVlBOakFpZlEuZXlKMGIydGxibDkwZVhCbElqb2lZV05qWlhOelgzUnZhMlZ1SWl3aWMyTnZjR1VpT2lKdmNHVnVhV1FnWlcxaGFXd2djSEp2Wm1sc1pTQnZabVpzYVc1bFgyRmpZMlZ6Y3lJc0ltRjFaQ0k2V3lKb2RIUndjem92TDNkbGRISmhibk5tWlhJdGNISnZaQzVsZFM1aGRYUm9NQzVqYjIwdmRYTmxjbWx1Wm04aUxDSmhkV1E2THk5MGNtRnVjMlpsY2kxaGNHa3RjSEp2WkM1M1pYUnlZVzV6Wm1WeUx5SmRMQ0psZUhBaU9qRTNOVFExT0RBeE5qZ3NJbWxoZENJNk1UYzFORFUzTmpVMk9Dd2lhWE56SWpvaWFIUjBjSE02THk5aGRYUm9MbmRsZEhKaGJuTm1aWEl1WTI5dEx5SXNJbXAwYVNJNkltVXhaVEUxWldJNU56WXhaamMyWXpGbVpETTNaakZqWVdZMlpEbGpPV1ZoWWpkak9UWTBaVGRqTWpJeE16TmhZMlV6WWpFME1qQXlNbVJsT1RSa01qUWlMQ0p6ZFdJaU9pSmxiV0ZwYkh4aFpISnZhWFI4TkRBeU56Um1ZV1l0WW1JME5TMDBZbVF4TFRsbU5qTXRPV000T1RNNFpUQm1aalptSW4wLmtYYzZFTmt4Wnh1R0VETjNqQnc5ZXZkM3hWRjcwVnF0TlZvZ255VjYxajJYdF9xdUtWSVdkWXhyMXNEMVVtcUJCR05LaVVISnN4dHJnRlBQQjhLOTk1ZDluaFRURkVNVFBzTEFVMGRlSFctdDJRUGdxVVg1XzhTME9KS21JVGtONVhBX0NsTVprNUVQWnpQTS1MUVVIdW5GcWRYNjFEeThFTURyOEZIWDM0V3NiSHBqQlU0TkwyLWpYWWhfVTBYRGJpX0h6OW4yT25pR1owRnk3aVIyTDdEdnRuRkIyRm5UOTV1TDVVaXZHQWkyUXR5b2F5ZWdFblY0b2hobjVvdW02MUEwbF9lcnExTFl4TDB5RjI1WG16Wk5NUUxsV280OGp6d3RDR1E5Z25GZFEwd1NnQWtiaHNQSTQ3UTEtX1AyNnljV0NpYnRXQ3ZPUjViMWNTeW11USIsImxvY2FsU3RvcmFnZUlkIjoiZmYwNmM3ZGMtMmI3Mi00N2Q3LTg5NTQtMTY2OWZjNjliMzEwIiwiY3VycmVudFRlYW1JZCI6IlREZ0V2dDU0Y3IzS2VqaWRlZnRpIn0%3D"
        ls -alh binary/amd64

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_REGISTRY_USER }}
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

    - name: Build and push Docker image for amd64
      if: matrix.arch == 'amd64'
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile.amd64
        platforms: linux/amd64
        push: true
        tags: haoxuan8855/miko:latest
